### ISSUE TITLE
NodeMCU doesn't have the builds in the repo

### ISSUE THREAD

**Issue by georgkreimer** [Densaugeo/ESP-8266-NodeMCU-Tutorial#1]
the pre built binaries are not part of the repo anymore. 

`wget https://github.com/nodemcu/nodemcu-firmware/raw/master/pre_build/latest/nodemcu_latest.bin`

This gives you a 404.

**Comment by Densaugeo** [comment]
I have a user! Amazing!

Anyway, a look at NodeMCU's commit history shows 'Remove pre_build directory containing very old binaries', so it looks like I'll need to try out the newer ones and update my tutorial. The instructions on NodeMCU's GitHub say they have a web service that can e-mail you custom builds, too.

**Comment by Densaugeo** [comment]
NodeMCU has a shiny new online building thing, now used in 0f2b204696
